---
- hosts: all
  become: yes

  vars:
    - venv: /usr/bin/.emacs.venv
      
  tasks:
  # Windows manager
  - name: Ensure I3 is installed.
    package:
      name:
        - i3
        - xinit
      state: present

  # Display manager
  - name: Ensure emptty dependencies are installed.
    package:
      name:
        - golang
        - libpam0g-dev
        - xorg
        - libxgks-dev
        - xauth
        - gcc
        - util-linux
        - git
      state: present
      
  - name: Ensure emptty source code is downloaded.
    ansible.builtin.git:
      repo: 'https://github.com/tvrzna/emptty'
      dest: /tmp/emptty
      version: d70822e745ef98c27d1b7c19d23de5d8b6e45877

  - name: Ensure emptty is compiled.
    community.general.make:
      chdir: /tmp/emptty

  - name: Ensure ly is installed.
    community.general.make:
      chdir: /tmp/emptty
      targets:
        - install
        - install-pam-debian
        - install-manual
        - install-config
        - install-systemd
      
  - name: Ensure emptty is running.
    service:
      name: emptty
      state: started
      enabled: yes

  - name: Unconditionally reboot the machine
    reboot:      
